### ISSUE TITLE
Also another issue

### ISSUE THREAD

**Issue by kaoti** [avocadoboi/AvoGUI#10]
Well, some objects dosnt respond to move and set pos functions in a certain points... like the text input bar, i set the y axis to the bottom of the screen and it stays on the center of the screen or just disppears!

**Comment by avocadoboi** [comment]
That sounds weird, could you post a minimal example?

**Comment by kaoti** [comment]
Sure

![image](https://user-images.githubusercontent.com/34654113/80804971-06591980-8bb7-11ea-9915-d85338f069b5.png)

**Comment by kaoti** [comment]
And this happens too, it disappears when its outside of some kind of container... 
![image](https://user-images.githubusercontent.com/34654113/80805448-571d4200-8bb8-11ea-82f0-4a5b43cb0636.png)

**Comment by avocadoboi** [comment]
I would suspect that the problem here is that you are not thinking about the coordinates as relative to the parent of the view. For example, if I write:
```cpp
auto container = new View(this);
container->setTopLeft(100);
container->setSize(300);

auto child = new View(container);
```
Now child is positioned at (100, 100) relative to the GUI, because the default top-left coordinates are (0, 0).

**Comment by kaoti** [comment]
I would love to learn to use this library because its beautiful! you should do tutorials about this api, i think that people will like it

**Comment by avocadoboi** [comment]
I've thought about making some tutorial about it, thanks for the motivation! Will do when I have time.

**Comment by kaoti** [comment]
Or create a full documentation on it... will be amazin would be

**Comment by avocadoboi** [comment]
Yes, might make some kind of website with documentation when the API is final enough, still making some big changes sometimes...

Did you understand what the problem was with your positioning? When you write getBottom() or getCenterY(), those coordinates are absolute and not relative to the parent of the view you're positioning. Also remember that child views are clipped by their parent, so if a child is outside of its parent, it's invisible. Also you might consider removing the container view completely and directly attach the text field to the GUI.

**Comment by kaoti** [comment]
Lol i didnt thought about that... and thats right, it works right now! thanks you!

**Comment by avocadoboi** [comment]
Nice! 
What you would write to center a view within a container would be:
```cpp
auto container = new View(this);
container->setSize(400, 300); // whatever

auto child = new View(container);
child->setCenter(container->getSize()/2.f);

// Now, if we move the container:
container->move(100, 200);
// The child will still be in the center of the container!
```

**Comment by kaoti** [comment]
Man, i admire you... wou wrote 26000 fucking c++ lines of code... its impressive, how much time did you spent in this project?

**Comment by avocadoboi** [comment]
Haha, it took a long time. The motivation has always been strong though, I made it because I was frustrated that there was no library that fit my "needs". When I first started programming, I made games with SFML. Then I started to make fun little JavaScript projects which I put on my website. I always wished I could make anything in c++, including those types of projects. I searched a lot for libraries but the best I could find was like Qt, which is GIANT and it's not fully open source. I wanted a clean library with a logical API that gives a lot of freedom and can be used to make graphical programs as good looking as what you can make with html, css and javascript. I also wanted the framework to hold for making large applications. 

I'm still working towards that goal, mainly by just making stuff with it and thinking about how it could be designed differently to work more smoothly, etc.

**Comment by kaoti** [comment]
You inspired me to make one gui system myself!!! thanks you!
