### ISSUE TITLE
Doesnt appear anything in the window until i maximize the window

### ISSUE THREAD

**Issue by kaoti** [avocadoboi/AvoGUI#9]
Well thats it, if there is a function like in c# that enable the contenent would be amazing!

**Comment by avocadoboi** [comment]
It appears that this is a bug from the version that is on the master branch, I recommend you use the linux-development branch instead. I haven't touched the master branch in months because I have been working on the other branch with adding support for linux. There are also some pretty big improvements to the framework that aren't on the master yet. I will merge the linux-development branch as soon as I have updated the example projects! Just make sure to take a look at the updated readme, specifically the part about the new event system. 
I'm glad you found my framework :)

**Comment by avocadoboi** [comment]
I have now merged into the master branch and created a stable first release, use that!

**Comment by kaoti** [comment]
Thanks! btw i love this library, and id love to participate developing it! if you need any kind of help on this project i will happily help you!!

**Comment by avocadoboi** [comment]
Makes me happy to hear! :^)

Right now the next long term goal is to fully support Linux. The main rendering pipeline with OpenGL is working, with shader-driven anti-aliasing, loading and drawing images, and drawing filled and stroked shapes. The next steps are:
* Updating the Linux code to work with the recent event system changes (have been working with projects on Windows for a while now).
* Implementing an anti-aliased shape clipping mechanism.
* Adding custom shape triangulation that works with the anti-aliasing system, which essentially requires setting certain vertex attributes that tell the shader which edges should be smoothed.
* Implementing gradients with variabe stops.
* Implementing more of the windowing functionality for LinuxWindow, something that is very needed is to handle more events. 
* Implementing OpenFileDialog, and now that I think of it, making a SaveFileDialog class and implementing it on Windows as well.

If you find anything you'd like to change or any functionality you want to add, feel free to contribute! Just reporting issues is very helpful as well. I'm still pretty new to open source collaboration, and I haven't made any guidelines yet. Don't worry about it though, I'll reformat the code as needed if it isn't perfect.
